name: Publish to PyPI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build dist
        run: |
          python -m build

      - name: Release to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1